### PR TITLE
Add myself and @vemel to maintainers, bump version

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
Greetings @thewchan! We seem to be simultaneously working on some type-checking packages. For instance, I'm trying to make a `boto3-stubs[essential]` package [here](https://github.com/conda-forge/boto3-stubs-feedstock/pull/7). I'm also proposing the missing stub packages [here](https://github.com/conda-forge/staged-recipes/pull/14923).

Would you be willing to allow me to add you as co-maintainer for these projects??? Thanks!

**Comment by thewchan** [comment]
Sure thing! @maresb
Please let me know how else I can help!

**Comment by maresb** [comment]
Excellent @thewchan! I have now added everywhere.

I forgot to mention the [mypy_boto3_builder feedstock](https://github.com/conda-forge/staged-recipes/pull/14915) where I also added you.

**Comment by maresb** [comment]
I'm not sure how much use `mypy_boto3_builder` will be, but I added it just in case.

In https://github.com/conda-forge/boto3-stubs-feedstock I added an output for `boto3-stubs-essential` which is meant to replicate `pip install boto3-stubs[essential]` by installing this `mypy_boto3_s3` package together with all the others in https://github.com/conda-forge/staged-recipes/pull/14923. I actually use `mypy_boto3_builder` here in the tests since it knows which packages are "essential".

There is a bit of a race condition which I'm not sure how to solve: boto3-stubs-essential depends on having access to all the stub packages, so building that package needs to be somehow deferred until those packages are posted to conda-forge and show up on the CDN. I may have to ask on Gitter about how to do this, unless you have any ideas.

Let me know if you have any questions, and thanks for your help!

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@thewchan I found [the author](https://github.com/conda-forge/boto3-feedstock/issues/468#issuecomment-841778808)! :smile:

I'm not sure why conda-forge-admin is not rerendering the README with @vemel as maintainer.

**Comment by maresb** [comment]
My other feedstocks got merged, so once they hit the CDN we'll be able to make `boto3-stubs-essential`.

**Comment by maresb** [comment]
@thewchan could we please merge this when you get the chance?

I have noticed an unfortunate naming inconsistency between this package which you created and the other packages which I created for boto3-stubs-essential. This uses `-` instead of `_`.

**Pull request merged**
